### ISSUE TITLE
Figure out user model

### ISSUE THREAD

**Issue by madbence** [madbence/spacegame#12]
It should support multiple providers:
- facebook
- google plus
- local (user + password)

**Comment by madbence** [comment]
@komigabor any progress?

**Comment by Thegaram** [comment]
I've looked at #84, but couldn't really make it work. What do you think of using [passport](http://passportjs.org/) for authentication? It supports local, Google, Facebook, etc. auth and seems fairly simple to use.

I'm not sure what's the right way to "protect" pages that need authentication (e.g. `/lobby`). The usual advice is to use two separate `koa-router` instances, something like this:

``` javascript
import router from 'koa-router';

const publicRouter = router();
// configure public routes...

const securedRouter = router();
securedRouter.use(middlewareThatChecksAuthentication);
// configure secured routes...

// combine...
```

Any ideas? Should we use this and switch to `koa-router` (instead of `koa-route`)?
